name: "Run ComfyUI on Various OSs"
description: "Run a comfyui workflow on various OSs"
inputs:
  os:
    description: "Operating System. macos, linux, windows."
    required: true
    default: ""
  python_version:
    description: "Python Version. Will be used in the conda install command for pytorch. 3.9 or 3.10. Only valid when os is linux or windows."
    required: false
    default: "3.9"
  cuda_version:
    description: "CUDA Version. Will be used in the conda install command for pytorch. 11.8 or 12.1. Only valid when os is linux or windows."
    required: false
    default: "12.1"
  torch_version:
    description: "Pytorch Version. Will be used in the conda install command for pytorch. 1.10.0 or 1.11.0. Only valid when os is linux or windows."
    required: false
    default: 'stable'
  models-json:
    description: 'JSON string containing models and their download URLs. The models will be downloaded into the exact directory relative to /ComfyUI/models/. eg { "model_name": { url: "https://example.com/model.pth", "directory": "checkpoints" } }'
    required: false
  workflow_filenames:
    description: "The list of workflow filenames is listed in the workflows/ directory. Separate by comma, e.g., 'workflow1.json,workflow2.json'."
    required: true
  comfyui_flags:
    description: "Flags to pass to the comfyui application. eg. --force-fp16"
    required: false
    default: ''
  # Not yet supported
  workflow_raw_json:
    description: "Workflow's raw json file"
    required: false
    default: ''
  timeout:
    description: "Timeout for the workflow (in seconds)"
    required: false
    default: "600"
  google_credentials:
    description: "Service Account JSON for uploading to GCS. Required if you want results uploaded to CI dashboard. http://www.comfyci.org"
    required: false
  gcs_bucket_name:
    description: "Name of the GCS bucket to upload the output files to. Required if you want results uploaded to CI dashboard. http://www.comfyci.org"
    required: false
    default: "comfy-ci-results"
  output_prefix:
    description: "Prefix for the output files. Required if you want results uploaded to CI dashboard. http://www.comfyci.org"
    required: false
    default: "ComfyUI"
  api_endpoint:
    description: "Comfy Org API endpoint"
    required: false
    default: "https://api.comfy.org/upload-artifact"
  skip_quickci:
    description: "Skip quickci."
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: '[Universal] Checkout'
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    ############################################################
    ##                      Mac/Linux Steps                   ##
    ##           ______________                               ##
    ##          /             /|              _nnnn_          ##
    ##         /             / |             dGGGGMMb         ##
    ##        /____________ /  |            @p~qp~~qMb        ##
    ##       | ___________ |   |            M|@||@) M|        ##
    ##       ||           ||   |            @,----.JM|        ##
    ##       ||           ||   |           JS^\__/  qKL       ##
    ##       ||           ||   |          dZP        qKRb     ##
    ##       ||___________||   |         dZP          qKKb    ##
    ##       |   _______   |  /         fZP            SMMb   ##
    ##      /|  (_______)  | /          HZM            MMMM   ##
    ##     ( |_____________|/           FqM            MMMM   ##
    ##      \                         __| ".        |\dS"qML  ##
    ##  .=======================.     |    `.       | `' \Zq  ##
    ##  | ::::::::::::::::  ::: |    _)      \.___.,|     .'  ##
    ##  | ::::::::::::::[]  ::: |    \____   )MMMMMP|   .'    ##
    ##  |   -----------     ::: |         `-'       `--'      ##
    ##  `-----------------------'                             ##
    ############################################################

    - name: Set up Node.js (required for using actions/github-script)
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Print Inputs
      uses: actions/github-script@v5
      with:
        script: |
          console.log(`Operating System: ${{ inputs.os }}`);
          console.log(`Python Version: ${{ inputs.python_version }}`);
          console.log(`CUDA Version: ${{ inputs.cuda_version }}`);
          console.log(`Pytorch Version: ${{ inputs.torch_version }}`);
          console.log(`Models JSON: ${{ inputs['models-json'] }}`);
          console.log(`Workflow Filenames: ${{ inputs.workflow_filenames }}`);
          console.log(`ComfyUI Flags: ${{ inputs.comfyui_flags }}`);
          console.log(`Workflow Raw JSON: ${{ inputs.workflow_raw_json }}`);
          console.log(`Timeout: ${{ inputs.timeout }}`);
          console.log(`Google Credentials: ${{ inputs.google_credentials }}`);
          console.log(`GCS Bucket Name: ${{ inputs.gcs_bucket_name }}`);
          console.log(`Output Prefix: ${{ inputs.output_prefix }}`);
          console.log(`API Endpoint: ${{ inputs.api_endpoint }}`);
          console.log(`Skip QuickCI: ${{ inputs.skip_quickci }}`);

    #####################################################################################
    ##                           Windows Steps (F**k powershell)                       ##
    ##                                                                                 ##
    ##               _.-;;-._      _                                                   ##
    ##        '-..-'|   ||   |    | |                                                  ##
    ##        '-..-'|_.-;;-._|    | |===( )   //////                                   ##
    ##        '-..-'|   ||   |    |_|   |||  | o o|                                    ##
    ##        '-..-'|_.-''-._|           ||| ( c  )                  ____              ##
    ##                                    ||| \= /                  ||   \_            ##
    ##                                     ||||||                   ||     |           ##
    ##                                     ||||||                ...||__/|-"           ##
    ##                                     ||||||             __|________|__           ##
    ##                                       |||             |______________|          ##
    ##                                       |||             || ||      || ||          ##
    ##                                       |||             || ||      || ||          ##
    ##  -------------------------------------|||-------------||-||------||-||-------   ##
    ##                                       |__>            || ||      || ||          ##
    ##                                                                                 ##
    ##                                                                                 ##
    #####################################################################################
