name: "Run ComfyUI on Various OSs"
description: "Run a comfyui workflow on various OSs"
inputs:
  os:
    description: "Operating System. macos, linux, windows."
    required: true
    default: ""
  python_version:
    description: "Python Version. Will be used in the conda install command for pytorch. 3.9 or 3.10. Only valid when os is linux or windows."
    required: false
    default: "3.9"
  cuda_version:
    description: "CUDA Version. Will be used in the conda install command for pytorch. 11.8 or 12.1. Only valid when os is linux or windows."
    required: false
    default: "12.1"
  torch_version:
    description: "Pytorch Version. Will be used in the conda install command for pytorch. 1.10.0 or 1.11.0. Only valid when os is linux or windows."
    required: false
    default: 'stable'
  models-json:
    description: 'JSON string containing models and their download URLs. The models will be downloaded into the exact directory relative to /ComfyUI/models/. eg { "model_name": { url: "https://example.com/model.pth", "directory": "checkpoints" } }'
    required: false
  workflow_filenames:
    description: "The list of workflow filenames is listed in the workflows/ directory. Separate by comma, e.g., 'workflow1.json,workflow2.json'."
    required: true
  comfyui_flags:
    description: "Flags to pass to the comfyui application. eg. --force-fp16"
    required: false
    default: ''
  # Not yet supported
  workflow_raw_json:
    description: "Workflow's raw json file"
    required: false
    default: ''
  timeout:
    description: "Timeout for the workflow (in seconds)"
    required: false
    default: "600"
  google_credentials:
    description: "Service Account JSON for uploading to GCS. Required if you want results uploaded to CI dashboard. http://www.comfyci.org"
    required: false
  gcs_bucket_name:
    description: "Name of the GCS bucket to upload the output files to. Required if you want results uploaded to CI dashboard. http://www.comfyci.org"
    required: false
  output_prefix:
    description: "Prefix for the output files. Required if you want results uploaded to CI dashboard. http://www.comfyci.org"
    required: false
    default: "ComfyUI"
  api_endpoint:
    description: "Comfy Org API endpoint"
    required: false
    default: "https://api.comfy.org/upload-artifact"
  conda_env_file:
    description: "Conda environment file. Path is relative to your repository root. The environment name must be comfyui."
    required: true
runs:
  using: "composite"
  steps:
    - name: '[Universal] Checkout'
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    ############################################################
    ##                      Mac/Linux Steps                   ##
    ##           ______________                               ##
    ##          /             /|              _nnnn_          ##
    ##         /             / |             dGGGGMMb         ##
    ##        /____________ /  |            @p~qp~~qMb        ##
    ##       | ___________ |   |            M|@||@) M|        ##
    ##       ||           ||   |            @,----.JM|        ##
    ##       ||           ||   |           JS^\__/  qKL       ##
    ##       ||           ||   |          dZP        qKRb     ##
    ##       ||___________||   |         dZP          qKKb    ##
    ##       |   _______   |  /         fZP            SMMb   ##
    ##      /|  (_______)  | /          HZM            MMMM   ##
    ##     ( |_____________|/           FqM            MMMM   ##
    ##      \                         __| ".        |\dS"qML  ##
    ##  .=======================.     |    `.       | `' \Zq  ##
    ##  | ::::::::::::::::  ::: |    _)      \.___.,|     .'  ##
    ##  | ::::::::::::::[]  ::: |    \____   )MMMMMP|   .'    ##
    ##  |   -----------     ::: |         `-'       `--'      ##
    ##  `-----------------------'                             ##
    ############################################################
    - name: 'Auth to GCS'
      uses: "google-github-actions/auth@v2"
      with:
        credentials_json: "${{ inputs.google_credentials }}"
  
    - name: '[Unix] Cache Conda'
      if: ${{ inputs.os != 'windows' }}
      uses: actions/cache@v4
      env:
          # Increase this value to reset cache if the environment file has not changed
          CACHE_NUMBER: 0
      with:
        path: ~/miniconda3/envs/comfyui
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles(format('{0}', inputs.conda_env_file)) }}
      
    - name: '[Unix] Setup Conda'
      uses: conda-incubator/setup-miniconda@v3
      if: ${{ inputs.os != 'windows' }}
      with:
        activate-environment: comfyui
        auto-activate-base: false
        environment-file: ${{ inputs.conda_env_file }}
        use-only-tar-bz2: true

    - name: '[Unix] Check conda environment'
      if: ${{ inputs.os != 'windows' }}
      run: |
        conda info
        conda list
      shell: bash -el {0}
    
    - name: '[Unix] Generate hash from models-json'
      if: ${{ inputs.os != 'windows' }}
      id: generate_hash
      run: |
        echo "hash=$(echo '${{ inputs.models-json }}' | sha256sum | cut -d ' ' -f1)" >> $GITHUB_OUTPUT
      shell: bash

    - name: '[Unix] Cache models'
      if: ${{ inputs.os != 'windows' }}
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/models
        key: ${{ runner.os }}-models-${{ steps.generate_hash.outputs.hash }}
  
    - name: '[Unix] Download models'
      if: ${{ inputs.os != 'windows' }}
      shell: bash -el {0}
      run: |
        cd ${{ github.action_path }}
        python3 download-models.py raw '${{ inputs.models-json }}' "${{ github.workspace }}/models/"
        
    - name: '[Unix] Run Python application in background'
      if: ${{ inputs.os != 'windows' }}
      shell: bash -el {0}
      run: |
        python3 main.py > application.log 2>&1 &

    - name: '[Unix] Check if the server is running'
      if: ${{ inputs.os != 'windows' }}
      run: |
        cd ${{ github.action_path }}
        python3 poll_server_start.py > application.log 2>&1
      shell: bash -el {0}

    - name: '[Unix] Get Commit Details'
      id: unix_get_commit_details
      if: ${{ inputs.os != 'windows' }}
      shell: bash -el {0}
      run: |
        TIMESTAMP=$(git show -s --format=%cI HEAD^)
        MESSAGE=$(git show -s --format=%s HEAD^)
        COMMIT_HASH=$(git rev-parse HEAD^)
        echo "Commit time: $TIMESTAMP"
        echo "Commit title: $MESSAGE"
        echo "Commit hash: $COMMIT_HASH"
        echo "commit_time=$TIMESTAMP" >> $GITHUB_OUTPUT
        echo "commit_title=$MESSAGE" >> $GITHUB_OUTPUT
        echo "commit_hash=$COMMIT_HASH" >> $GITHUB_OUTPUT

    - name: '[Unix] Queue Prompts'
      id: unix_queue_prompt
      if: ${{ inputs.os != 'windows' }}
      shell: bash -el {0}
      run: |
        cd ${{ github.action_path }}
        echo "Running workflows: ${{inputs.workflow_filenames}}"
        python3 queue_prompt.py --comfy-workflow-names ${{ inputs.workflow_filenames }} --github-action-workflow-name "${{ github.workflow }}" --os "${{ inputs.os }}" --run-id "${{ github.run_id }}" --gsc-bucket-name "${{ inputs.gcs_bucket_name }}" --workspace-path "${{ github.workspace }}" --output-file-prefix ${{ inputs.output_prefix }} --repo "${{ github.repository }}" --commit-hash "${{ steps.unix_get_commit_details.outputs.commit_hash }}" --commit-time "${{ steps.unix_get_commit_details.outputs.commit_time }}" --commit-message "${{ steps.unix_get_commit_details.outputs.commit_title }}" --branch-name "${{ github.ref_name }}" --api-endpoint "${{ inputs.api_endpoint }}" 

    - name: '[Unix] Upload log file'
      if: ${{ inputs.os != 'windows' }}
      uses: actions/upload-artifact@v4
      with:
        name: app-logs-${{ github.job }}-${{ inputs.os }}-${{inputs.workflow_name}}-${{ github.run_id }}
        path: ${{ github.workspace }}/application.log

    # - name: '[Unix] Cleanup Repo'
    #   if: ${{ inputs.os != 'windows' && ( success() || failure() ) }}
    #   shell: bash -el {0}
    #   run: rm -rf ${{ github.workspace }}/*

    # - name: '[Unix] Cleanup Conda'
    #   if: ${{ inputs.os != 'windows' && ( success() || failure() ) }}
    #   shell: bash -el {0}
    #   run: conda deactivate && conda env remove --name comfyui && conda clean -all


    #####################################################################################
    ##                           Windows Steps (F**k powershell)                       ##
    ##                                                                                 ##
    ##               _.-;;-._      _                                                   ##
    ##        '-..-'|   ||   |    | |                                                  ##
    ##        '-..-'|_.-;;-._|    | |===( )   //////                                   ##
    ##        '-..-'|   ||   |    |_|   |||  | o o|                                    ##
    ##        '-..-'|_.-''-._|           ||| ( c  )                  ____              ##
    ##                                    ||| \= /                  ||   \_            ##
    ##                                     ||||||                   ||     |           ##
    ##                                     ||||||                ...||__/|-"           ##
    ##                                     ||||||             __|________|__           ##
    ##                                       |||             |______________|          ##
    ##                                       |||             || ||      || ||          ##
    ##                                       |||             || ||      || ||          ##
    ##  -------------------------------------|||-------------||-||------||-||-------   ##
    ##                                       |__>            || ||      || ||          ##
    ##                                                                                 ##
    ##                                                                                 ##
    #####################################################################################

    - name: '[Windows] Cache Conda'
      if: ${{ inputs.os != 'windows' }}
      uses: actions/cache@v4
      env:
          # Increase this value to reset cache if the environment file has not changed
          CACHE_NUMBER: 0
      with:
        path: C:\Miniconda3\envs\comfyui
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles(format('{0}', inputs.conda_env_file)) }}

    - name: '[Win] Setup Conda'
      uses: conda-incubator/setup-miniconda@v3
      if: ${{ inputs.os == 'windows' }}
      with:
        activate-environment: comfyui
        auto-activate-base: false
        auto-update-conda: true
        miniconda-version: 24.5.0
        environment-file: ${{ inputs.conda_env_file }}
        use-only-tar-bz2: true

    - name: "[Win] Check conda environment"
      if: ${{ inputs.os == 'windows' }}
      run: |
        conda info
        conda list
      shell: powershell

    - name: Generate hash from models-json
      if: ${{ inputs.os == 'windows' }}
      id: generate_hash_windows
      run: |
        $hash = (Get-FileHash -Algorithm SHA256 -InputStream ([System.IO.MemoryStream][System.Text.Encoding]::UTF8.GetBytes("${{ inputs.models-json }}"))).Hash
        echo "hash=$hash" >> $GITHUB_OUTPUT
      shell: powershell

    - name: '[Windows] Cache models'
      if: ${{ inputs.os == 'windows' }}
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/models
        key: ${{ runner.os }}-models-${{ steps.generate_hash_windows.outputs.hash }}

    # Keep in mind the self runner must be setup with a model in C:\actions-runner\
    # - name: '[Win] Download models'
    #   if: ${{ inputs.os == 'windows' }}
    #   run: |
    #     cd $Env:GITHUB_ACTION_PATH
    #     ls "$Env:GITHUB_WORKSPACE"
    #     cp "C:\actions-runner\v1-5-pruned-emaonly.ckpt" "$Env:GITHUB_WORKSPACE/models/checkpoints"
    #   shell: powershell

    - name: '[Windows] Download models'
      if: ${{ inputs.os == 'windows' }}
      shell: powershell
      run: |
        Set-Location ${{ env.GITHUB_ACTION_PATH }}
        python download-models.py raw "${{ inputs.models-json }}" "${{ env.GITHUB_WORKSPACE }}\models\"

    - name: '[Win] Run Python application'
      if: ${{ inputs.os == 'windows' }}
      shell: powershell
      run: |
        $envGithubWorkspace = $Env:GITHUB_WORKSPACE
        Write-Output "##############################"
        Write-Output $envGithubWorkspace
        Write-Output "##############################"
        Start-Process powershell -ArgumentList "-File", "${{ github.action_path }}\start-server.ps1", "-GITHUB_WORKSPACE", "`"$envGithubWorkspace`""

    - name: '[Win] Check if the server is running'
      if: ${{ inputs.os == 'windows' }}
      run: |
        cd $Env:GITHUB_ACTION_PATH
        python poll_server_start.py
      shell: powershell

    - name: '[Win] Get Commit Details'
      id: win_get_commit_details
      if: ${{ inputs.os == 'windows' }}
      shell: powershell
      run: |
        $timestamp = git show -s --format=%cI HEAD^
        $message = git show -s --format=%s HEAD^
        $commit_hash = git rev-parse HEAD^
        "commit_time=$timestamp" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append
        "commit_title=$message" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append
        "commit_hash=$commit_hash" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append

    - name: '[Windows] Queue Prompts'
      id: windows_queue_prompt
      if: ${{ inputs.os == 'windows' }}
      shell: powershell
      run: |
        Set-Location ${{ env.GITHUB_ACTION_PATH }}
        Write-Host "Running workflows: ${{ inputs.workflow_filenames }}"
        python queue_prompt.py `
          --comfy-workflow-names "${{ inputs.workflow_filenames }}" `
          --github-action-workflow-name "${{ github.workflow }}" `
          --os "${{ inputs.os }}" `
          --run-id "${{ github.run_id }}" `
          --gsc-bucket-name "${{ inputs.gcs_bucket_name }}" `
          --workspace-path "${{ github.workspace }}" `
          --output-file-prefix "${{ inputs.output_prefix }}" `
          --repo "${{ github.repository }}" `
          --commit-hash "${{ steps.win_get_commit_details.outputs.commit_hash }}" `
          --commit-time "${{ steps.win_get_commit_details.outputs.commit_time }}" `
          --commit-message "${{ steps.win_get_commit_details.outputs.commit_title }}" `
          --branch-name "${{ github.ref_name }}" `
          --api-endpoint "${{ inputs.api_endpoint }}"

    - name: '[Win] Upload Output Files'
      uses: actions/upload-artifact@v4
      if: ${{ inputs.os == 'windows' && ( success() || failure() ) }}
      with:
        name: output-files-${{ github.job }}-${{ inputs.os }}-${{inputs.workflow_name}}-${{ github.run_id }}
        path: ${{ github.workspace }}/output/**

    - name: '[Win] Upload log file'
      uses: actions/upload-artifact@v4
      if: ${{ inputs.os == 'windows' && ( success() || failure() ) }}
      with:
        name: app-logs-${{ github.job }}-${{ inputs.os }}-${{inputs.workflow_name}}-${{ github.run_id }}
        path: ${{ github.workspace }}/application.log
