name: 'Run ComfyUI on macOS'
description: 'Run a comfyui workflow on mac'
inputs:
  ORG_KEY:
    description: ''
    required: true
  py_ver:
    description: 'Python version'
    required: false
    default: "3.11"
  torch_ver:
    description: 'Pytorch version. Can be nightly or stable'
    required: false
    default: "stable"
  models-json:
    description: 'JSON string containing models and their download URLs. The models will be downloaded into the exact directory relative to /ComfyUI/models/. eg { "model_name": { url: "https://example.com/model.pth", "directory": "checkpoints" } }'
    required: true
  workflow:
    description: 'Workflow JSON to run'
    required: true
    default: "default"
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        
    - name: Clone ComfyUI repository
      shell: bash
      run: |
        git clone https://github.com/comfyanonymous/ComfyUI

    - name: Install Miniconda
      shell: bash
      run: |
        mkdir -p ~/miniconda3
        curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh -o ~/miniconda3/miniconda.sh
        bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
        rm -rf ~/miniconda3/miniconda.sh
        ~/miniconda3/bin/conda init bash

    - name: Download models
      working-directory: ~/ComfyUI
      run: python3 download-models.py "${{ inputs.models-json }}"
      shell: bash
    
    # https://developer.apple.com/metal/pytorch/
    # Install pytorch nightly
    - name: Create Conda environment
      shell: bash
      run: |
        conda create -n comfyui python=${{ inputs.py_ver }}
        conda activate comfyui
        conda install pytorch torchvision torchaudio -c pytorch-nightly

    - name: Install dependencies
      shell: bash
      working-directory: ~/ComfyUI
      run: |
        pip3 install -r requirements.txt
    
    - name: Run Python application
      shell: bash
      working-directory: ~/ComfyUI
      run: python3 main.py --force-fp16