name: Verify GitHub Action YML

on:
  push:
    paths:
      - 'action.yml'
      - 'action_yaml_checker.py'
      - '.github/workflows/verify-action.yml'
  workflow_dispatch: 

jobs:
  lint:
    name: Lint YAML files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install actionlint
      run: |
        curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash
        sudo mv actionlint /usr/local/bin/

    - name: Lint GitHub Actions workflows
      run: |
        actionlint

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt
        
    - name: Run action_yaml_checker.py
      run: python action_yaml_checker.py action.yml

