name: Verify GitHub Action YML

on:
  push:
    paths:
      - '.github/workflows/*.yml'
  pull_request:
    paths:
      - '.github/workflows/*.yml'
  workflow_dispatch: 

jobs:
  lint:
    name: Lint YAML files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install actionlint
      run: |
        curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash
        sudo mv actionlint /usr/local/bin/

    - name: Lint GitHub Actions workflows
      run: |
        actionlint

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip install requirements-dev.txt
        
    - name: Run action_yaml_checker.py
      run: python action_yaml_checker.py

